version: "2"
services:
  elasticsearch:
    image: elasticsearch:2
    command: [
      -Des.script.inline=on,
      -Des.cluster.name=hive,
      -Des.threadpool.index.queue_size=100000,
      -Des.threadpool.search.queue_size=100000,
      -Des.threadpool.bulk.queue_size=1000]
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data


  cortex:
    image: certbdf/cortex:latest
    ports:
      - "127.0.0.1:9001:9000"
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf       
        
  thehive:
    image: certbdf/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "127.0.0.1:9000:9000"

    volumes:
      - ./hive/application.conf:/etc/thehive/application.conf




#networks:
#  mynet:
#    driver: bridge
#    ipam:
#      config:
#      - subnet: 172.25.0.0/24
