version: "2"

#build:
#  context: ../MISP/MyOrg

services:
  elasticsearch:
    image: elasticsearch:2
    command: [
      -Des.script.inline=on,
      -Des.cluster.name=hive,
      -Des.threadpool.index.queue_size=100000,
      -Des.threadpool.search.queue_size=100000,
      -Des.threadpool.bulk.queue_size=1000]
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data


  cortex:
    image: certbdf/cortex:latest
    ports:
      - "127.0.0.1:9001:9000"
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf       
        
  thehive:
    image: certbdf/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
      - misp
    ports:
      - "127.0.0.1:9000:9000"

    volumes:
      - ./hive/application.conf:/etc/thehive/application.conf
  misp_db:
    build:
      context: ../MISP/MyOrg
    image: my_org_misp
    command:
     -  /init-db
    volumes:
     - /tmp/misp-db-myorg:/var/lib/mysql

  misp:
    depends_on:
      - misp_db
    image: my_org_misp
    ports:
     - "127.0.0.1:10443:443"
     - "127.0.0.1:10080:80"
     - "127.0.0.1:10666:6666"
    volumes:
     - /tmp/misp-db-myorg:/var/lib/mysql





#networks:
#  mynet:
#    driver: bridge
#    ipam:
#      config:
#      - subnet: 172.25.0.0/24
